version: '3.8'

services:
  db:
    image: postgres:15
    container_name: todo-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - todo-net

  backend:
    build: ./backend
    container_name: todo-backend
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_NAME: todo_db
      DB_PORT: 5432
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - todo-net

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - todo-net
    environment:
      VITE_API_ROOT: http://localhost:5000

volumes:
  pgdata:

networks:
  todo-net:
